name: haptic_morse
description: Convert text to Morse code and haptic vibration patterns in Dart.
version: 1.0.2
repository: https://github.com/Crdzbird/haptic_morse
topics:
  - morse
  - haptic
  - vibration
platforms:
  android:
  ios:
  macos:
  linux:
  windows:

homepage: https://github.com/Crdzbird/haptic_morse

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
