name: haptic_morse
description: Convert text to Morse code and haptic vibration patterns in Dart.
version: 1.0.5
repository: https://github.com/Crdzbird/haptic_morse
topics:
  - morse
  - haptic
  - vibration
platforms:
  android:
  ios:
  macos:
  linux:
  windows:

homepage: https://github.com/Crdzbird/haptic_morse

environment:
  sdk: ^3.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.0
dependencies:
  vibration: ^3.1.3
